version: '3.8'

services:
  finance-pg:
    image: postgres:17.3
    container_name: finance-pg-17.3
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - finance-pg-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  finance-pg-data: